// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmcklqjtktotuqouqqik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY2tscWp0a3RvdHVxb3VxcWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTE2MTQsImV4cCI6MjA2OTEyNzYxNH0.dtms5SajBvl_hiSZ8oy_Oeuv0-MOrZgkcbvRME3z3eM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});